---
name: Custom Issue
description: File a custom issue
title: "[Request]: "
labels: ["feature", "request"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this request!
  - type: textarea
    id: what-happened
    attributes:
      label: What would you like to experience?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you want to see!
      value: I would like to ....
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.1.2 (PRODUCTION)
        - 1.1.3 (APLHA)
    validations:
      required: true
  - type: dropdown
    id: platforms
    attributes:
      label: What platform are you using?
      multiple: true
      options:
        - iOS
        - Android
        - Windows
        - else
  - type: textarea
    id: tech notes
    attributes:
      label: technical notes
      description: Please share technical notes. This will be automatically formatted into code, so no need for backticks.
      render: shell
