---
name: Custom Issue
description: File a custom issue
title: "[Request]: "
labels: ["feature", "request"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this request!
  - type: textarea
    id: what-happened
    attributes:
      label: What would you like to experience?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you want to see!
      value: I would like to ....
    validations:
      required: true

