on:
  issues:
    types: [ opened ] # created, assigned, unassigned, labeled, unlabeled, opened, edited, milestoned, demilestoned, closed, reopened

jobs:
  issue_job:
    runs-on: ubuntu-latest
    steps:
      - name: View issue information
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
        run: |
          # https://github.community/t/get-contents-body-of-issue-in-action/136057/2
          echo "Issue title: $ISSUE_TITLE"
          echo "Issue body: $ISSUE_BODY"

      - name: View the github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_EVENT: ${{ github.event_path }}
        run: |
          echo "$GITHUB_CONTEXT"
          echo "$GITHUB_EVENT"

      - name: Issue Job
        uses: actions/github-script@v5
        env:
          ISSUE_BODY: ${{ github.event.issue.body }}
        with:
          script: |
            # https://github.com/actions/github-script#comment-on-an-issue
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'repeat: `${ISSUE_BODY}`'
            })