on:
  issues:
    types: [ opened ] # created, assigned, unassigned, labeled, unlabeled, opened, edited, milestoned, demilestoned, closed, reopened

jobs:
  issue_job:
    runs-on: ubuntu-latest
    steps:
      # https://github.community/t/get-contents-body-of-issue-in-action/136057/2
      # https://github.com/actions/github-script#comment-on-an-issue
      - name: Create Issue Comment
        uses: actions/github-script@v5
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
        with:
          script: |
            const { ISSUE_TITLE, ISSUE_BODY } = process.env
            console.log(`title: ${ISSUE_TITLE} - body ${ISSUE_BODY}`)
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Just to confirm, we are on it.\n---------\ntitle:\n**${ISSUE_TITLE}**\n\nrequest:\n${ISSUE_BODY}`
            })

      - name: Github Context View
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_EVENT: ${{ github.event_path }}
        run: |
          echo "$GITHUB_CONTEXT"
          echo "$GITHUB_EVENT"
