on:
  issues:
    types: [ opened ] # created, assigned, unassigned, labeled, unlabeled, opened, edited, milestoned, demilestoned, closed, reopened

jobs:
  issue_job:
    runs-on: ubuntu-latest
    steps:
      - name: View issue information
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
        run: |
          # https://github.community/t/get-contents-body-of-issue-in-action/136057/2
          echo "Issue title: $ISSUE_TITLE"
          echo "Issue body: $ISSUE_BODY"
          while read line; 
          do 
            #echo "line: '${line}'"; 
            if [[ $a == "- " ]];
            then
              echo '${line}'
            fi
          done < <(echo "$ISSUE_BODY")
      - name: View the github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_EVENT: ${{ github.event_path }}
        run: |
          echo "$GITHUB_CONTEXT"
          echo "$GITHUB_EVENT"