on:
  issues:
    types: [ opened ] # created, assigned, unassigned, labeled, unlabeled, opened, edited, milestoned, demilestoned, closed, reopened

jobs:
  issue_job:
    runs-on: ubuntu-latest
    steps:
      - name: Issue Job
        uses: actions/github-script@v5
        env:
          ISSUE_BODY: '${{ github.event.issue.body }}'
        with:
          script: |
            # https://github.com/actions/github-script#comment-on-an-issue
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for your issue!'
            })
            const issueBody = `${SHA}`
            console.log(issueBody)
