on:
  issues:
    types: [ opened ] # created, assigned, unassigned, labeled, unlabeled, opened, edited, milestoned, demilestoned, closed, reopened

jobs:
  issue_job:
    runs-on: ubuntu-latest
    steps:
      - name: View issue information
        run: |
          # https://github.community/t/get-contents-body-of-issue-in-action/136057/2
          echo "Issue title: ${{ github.event.issue.title }}"
          echo "Issue body: ${{ github.event.issue.body }}"
      - name: View the github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_EVENT: ${{ github.event_path }}
        run: |
          echo "$GITHUB_CONTEXT"
          echo "$GITHUB_EVENT"
          # body="$(jq '.event.issue.body' ${{ toJson(github) }})"
          # echo "$body"
