on:
  issues:
    types: [ opened ] # created, assigned, unassigned, labeled, unlabeled, opened, edited, milestoned, demilestoned, closed, reopened

jobs:
  issue_job:
    runs-on: ubuntu-latest
    steps:
      - name: Issue Job
        uses: actions/github-script@v5
        with:
          script: |
            # https://github.com/actions/github-script#comment-on-an-issue
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Thanks for your contribution! 👋'
            })
      - name: View issue information
        run: |
          # https://github.community/t/get-contents-body-of-issue-in-action/136057/2
          echo "Issue title: ${{ github.event.issue.title }}"
          echo "Issue body: ${{ github.event.issue.body }}"
      - name: View the github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
